CREATE TABLE MIDIA (
	ID INT NOT NULL,
	TITLE VARCHAR(30) NOT NULL, 
	DESCRIPTION VARCHAR(150) NOT NULL,
	URL VARCHAR(50) NOT NULL	
);

INSERT INTO MIDIA (ID, TITLE, DESCRIPTION, URL) VALUES (1, 'galas_feios', 'live dos galas', 'you.be/galas');
INSERT INTO MIDIA (ID, TITLE, DESCRIPTION, URL) VALUES (2, 'mikannn', 'live', 'you.be/mik');